define anton = Character('Антон', color="#5255ff")
define mother = Character('Мать', color="#c8ffc8")
define timoha = Character('Тимоха', color="#ff0000")
define father = Character('Отец', color="#00ffea")
define customer = Character('Заказчик')